# Generated by Django 4.1.4 on 2022-12-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_shop_app', '0002_alter_clothes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='sizes_available',
            field=models.CharField(default='M', max_length=50),
        ),
    ]
